### ISSUE TITLE
Null pointer exception when shutting down server

### ISSUE THREAD

**Issue by nandika** [wso2-attic/carbon-gateway-framework#54]
Null pointer exceptions is thrown when the server is shutdown with ^c. This is random error. 
Java version java version "1.8.0_73"

[2016-10-21 11:14:33,124] ERROR {org.wso2.carbon.transport.http.netty} - [SCR] Exception occurred while unbinding reference Reference[name = message-processor, interface = org.wso2.carbon.messaging.CarbonMessageProcessor, policy = dynamic, cardinality = 0..1, target = null, bind = addMessageProcessor, unbind = removeMessageProcessor]
    Details:
    Problematic reference = Reference[name = message-processor, interface = org.wso2.carbon.messaging.CarbonMessageProcessor, policy = dynamic, cardinality = 0..1, target = null, bind = addMessageProcessor, unbind = removeMessageProcessor]
    of service component = org.wso2.carbon.transport.http.netty.internal.HTTPTransportServiceComponent
    component implementation class = org.wso2.carbon.transport.http.netty.internal.HTTPTransportServiceComponent
    located in bundle with symbolic name = org.wso2.carbon.transport.http.netty
    bundle location = reference:file:../../plugins/org.wso2.carbon.transport.http.netty_2.1.9.SNAPSHOT.jar java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.eclipse.equinox.internal.ds.model.ComponentReference.unbind(ComponentReference.java:476)
    at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.unbindReference(ServiceComponentProp.java:617)
    at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.unbind(ServiceComponentProp.java:262)
    at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.dispose(ServiceComponentProp.java:388)
    at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.dispose(ServiceComponentProp.java:102)
    at org.eclipse.equinox.internal.ds.InstanceProcess.disposeInstances(InstanceProcess.java:366)
    at org.eclipse.equinox.internal.ds.InstanceProcess.disposeInstances(InstanceProcess.java:306)
    at org.eclipse.equinox.internal.ds.Resolver.disposeComponentConfigs(Resolver.java:724)
    at org.eclipse.equinox.internal.ds.Resolver.disableComponents(Resolver.java:700)
    at org.eclipse.equinox.internal.ds.SCRManager.stoppingBundle(SCRManager.java:554)
    at org.eclipse.equinox.internal.ds.SCRManager.bundleChanged(SCRManager.java:233)
    at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:902)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
    at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
    at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:165)
    at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:75)
    at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:67)
    at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:102)
    at org.eclipse.osgi.container.Module.publishEvent(Module.java:466)
    at org.eclipse.osgi.container.Module.doStop(Module.java:624)
    at org.eclipse.osgi.container.Module.stop(Module.java:488)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1623)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1542)
    at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:248)
    at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:145)
    at org.eclipse.osgi.container.Module.doStop(Module.java:626)
    at org.eclipse.osgi.container.Module.stop(Module.java:488)
    at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:186)
    at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:160)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at org.wso2.carbon.transport.http.netty.internal.HTTPTransportContextHolder.removeMessageProcessor(HTTPTransportContextHolder.java:79)
    at org.wso2.carbon.transport.http.netty.internal.HTTPTransportServiceComponent.removeMessageProcessor(HTTPTransportServiceComponent.java:69)
    ... 34 more

**Comment by maheshika** [comment]
Closed, since the repo is deprecated.
